// image onebackroute_oneImg.js
export { default as CareQualityCommissionCqcOverviewImage } from "./CareQualityCommissionCqcOverviewImage.svg";

// images multi-page-scricpt.js
export { default as CqcFundamentalStandardsImage } from "./CqcFundamentalStandardsImage.svg";
export { default as img1ScopeOfRegistrationImage } from "./img1ScopeOfRegistrationImage.svg";
export { default as img2ScopeOfRegistrationImage } from "./img2ScopeOfRegistrationImage.svg";
export { default as img3ScopeOfRegistrationImage } from "./img3ScopeOfRegistrationImage.svg";

// Identity Gram
export { default as ColorLegendsImage } from "./ColorLegendsImage.svg";
export { default as IconIg1 } from "./icon-ig1.svg";
export { default as IconIg2 } from "./icon-ig2.svg";
export { default as IconIg3 } from "./icon-ig3.svg";
export { default as IconIg4 } from "./icon-ig4.svg";
export { default as IconIg5 } from "./icon-ig5.svg";
export { default as IconIg6 } from "./icon-ig6.svg";
export { default as IconIg7 } from "./icon-ig7.svg";
export { default as IconIg8 } from "./icon-ig8.svg";
export { default as IconIg9 } from "./icon-ig9.svg";
export { default as IconIg10 } from "./icon-ig10.svg";
export { default as IconIg11 } from "./icon-ig11.svg";
export { default as IconIg12 } from "./icon-ig12.svg";
export { default as IconIg13 } from "./icon-ig13.svg";
export { default as IconIg14 } from "./icon-ig14.svg";
export { default as IconIg15 } from "./icon-ig15.svg";
export { default as IconIg16 } from "./icon-ig16.svg";
export { default as IconIg17 } from "./icon-ig17.svg";
export { default as IconIg18 } from "./icon-ig18.svg";
export { default as IconIg19 } from "./icon-ig19.svg";
export { default as IconIg20 } from "./icon-ig20.svg";
export { default as IconIg21 } from "./icon-ig21.svg";
export { default as IconIg22 } from "./icon-ig22.svg";
export { default as IconIg23 } from "./icon-ig23.svg";
export { default as IconIg24 } from "./icon-ig24.svg";
export { default as IconIg25 } from "./icon-ig25.svg";
export { default as IconArrowSquareLeft } from "./arrow-square-left.svg";
export { default as ProductDiagram1 } from "./ProductDiagram1.svg";
export { default as ProductDiagram2 } from "./ProductDiagram2.svg";
export { default as BackIconPD } from "./BackIconPD.svg";


// IG Release 1st
export { default as IgProductDiagramRelease1Image } from "./IgProductDiagramRelease1Image.svg";
export { default as IgSalesiteFrontendApplicationImage } from "./IgSalesiteFrontendApplicationImage.svg";
export { default as IgSignupProcess2Image } from "./IgSignupProcess2Image.svg";
export { default as FillRegistrationForm21Image } from "./FillRegistrationForm21Image.svg";
export { default as ThroughGoogleOrOutlook22Image } from "./ThroughGoogleOrOutlook22Image.svg";
export { default as VerificationEmail221Image } from "./VerificationEmail221Image.svg";
export { default as AccountLinkSuccessfully222Image } from "./AccountLinkSuccessfully222Image.svg";
export { default as IgKnowYourCustomer31Image } from "./IgKnowYourCustomer31Image.svg";
export { default as IdentityVerificationService311Image } from "./IdentityVerificationService311Image.svg";
export { default as IgKnowYourBusiness32Image } from "./IgKnowYourBusiness32Image.svg";
export { default as CompanyVerification321Image } from "./CompanyVerification321Image.svg";
export { default as IgAuthorisedUser4Image } from "./IgAuthorisedUser4Image.svg";
export { default as System5Image } from "./System5Image.svg";
export { default as IndividualUserEmployee51Image } from "./IndividualUserEmployee51Image.svg";
export { default as CompanyAdmin52Image } from "./CompanyAdmin52Image.svg";
export { default as Dashboard521Image } from "./Dashboard521Image.svg";
export { default as CountWidget5211Image } from "./CountWidget5211Image.svg";
export { default as VerificationStatus5212Image } from "./VerificationStatus5212Image.svg";
export { default as RecentVerificationGridView5213Image } from "./RecentVerificationGridView5213Image.svg";
export { default as Teams522Image } from "./Teams522Image.svg";
export { default as AddUser5221Image } from "./AddUser5221Image.svg";
export { default as ViewUserList5222Image } from "./ViewUserList5222Image.svg";
export { default as ActiveInactiveUser5223Image } from "./ActiveInactiveUser5223Image.svg";
export { default as SelectService5231Image } from "./SelectService5231Image.svg";
export { default as SelectUser5232Image } from "./SelectUser5232Image.svg";
export { default as IgCompanyadminVerification523Image } from "./IgCompanyadminVerification523Image.svg";
export { default as Reports524Image } from "./Reports524Image.svg";
export { default as SelectDocument5241Image } from "./SelectDocument5241Image.svg";
export { default as ViewInformationComponents5242Image } from "./ViewInformationComponents5242Image.svg";
export { default as Integration525Image } from "./Integration525Image.svg";
export { default as ViewIntegration5251Image } from "./ViewIntegration5251Image.svg";
export { default as AddIntegration5252Image } from "./AddIntegration5252Image.svg";
// export { default as CqcFundamentalStandardsImage } from "./CqcFundamentalStandardsImage.svg";
// export { default as img1ScopeOfRegistrationImage } from "./img1ScopeOfRegistrationImage.svg";
// export { default as img2ScopeOfRegistrationImage } from "./img2ScopeOfRegistrationImage.svg";
// export { default as img3ScopeOfRegistrationImage } from "./img3ScopeOfRegistrationImage.svg";
// export { default as img1IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img1IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
// export { default as img2IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img2IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
// export { default as img3IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img3IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
// export { default as img4IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img4IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
// export { default as img5IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img5IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
// export { default as img6IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img6IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
// export { default as img7IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img7IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
// export { default as img8IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img8IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
export { default as RequiredMembershipsImage } from "./RequiredMembershipsImage.svg";
export { default as colorLegends } from "./colorLegends.svg";
export { default as img1IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img1IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg";
export { default as img2IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img2IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg";
export { default as img3IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img3IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg";
export { default as img4IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img4IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg";
export { default as img5IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img5IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg";
export { default as img6IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img6IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg";
export { default as img7IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img7IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg";
export { default as img8IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img8IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg"; export { default as PurposeOfProductCertificationImage } from "./PurposeOfProductCertificationImage.svg";
export { default as IgRequiredMembershipsCsaCloudSecurityAllianceWhereToApplyImage } from "./IgRequiredMembershipsCsaCloudSecurityAllianceWhereToApplyImage.svg";
export { default as IgRequiredMembershipsCsaCloudSecurityAllianceEligibilityCriteriaGdprImage } from "./IgRequiredMembershipsCsaCloudSecurityAllianceEligibilityCriteriaGdprImage.svg";
export { default as IgRequiredMembershipsCsaCloudSecurityAllianceApplicationProcessImage } from "./IgRequiredMembershipsCsaCloudSecurityAllianceApplicationProcessImage.svg";
export { default as IgRequiredMembershipsCsaCloudSecurityAllianceRequiredDocumentsImage } from "./IgRequiredMembershipsCsaCloudSecurityAllianceRequiredDocumentsImage.svg";
export { default as IgRequiredMembershipsCsaCloudSecurityAllianceCostBreakdownImage } from "./IgRequiredMembershipsCsaCloudSecurityAllianceCostBreakdownImage.svg";
export { default as IgRequiredMembershipsCsaCloudSecurityAllianceTimelineForCertificationImage } from "./IgRequiredMembershipsCsaCloudSecurityAllianceTimelineForCertificationImage.svg";
export { default as IgRequiredMembershipsCsaCloudSecurityAllianceValidityOfTheCertificateImage } from "./IgRequiredMembershipsCsaCloudSecurityAllianceValidityOfTheCertificateImage.svg";
