// image onebackroute_oneImg.js
export { default as CareQualityCommissionCqcOverviewImage } from "./CareQualityCommissionCqcOverviewImage.svg";

// images multi-page-scricpt.js
export { default as CqcFundamentalStandardsImage } from "./CqcFundamentalStandardsImage.svg";
export { default as img1ScopeOfRegistrationImage } from "./img1ScopeOfRegistrationImage.svg";
export { default as img2ScopeOfRegistrationImage } from "./img2ScopeOfRegistrationImage.svg";
export { default as img3ScopeOfRegistrationImage } from "./img3ScopeOfRegistrationImage.svg";
// export { default as img1IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img1IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
// export { default as img2IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img2IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
// export { default as img3IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img3IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
// export { default as img4IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img4IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
// export { default as img5IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img5IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
// export { default as img6IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img6IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
// export { default as img7IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img7IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
// export { default as img8IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img8IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
export { default as RequiredMembershipsImage } from "./RequiredMembershipsImage.svg";
export { default as colorLegends } from "./colorLegends.svg";
export { default as img1IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img1IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg";
export { default as img2IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img2IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg";
export { default as img3IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img3IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg";
export { default as img4IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img4IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg";
export { default as img5IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img5IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg";
export { default as img6IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img6IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg";
export { default as img7IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img7IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg";
export { default as img8IgRequiredMembershipsCsaCloudSecurityAllianceImage } from "./img8IgRequiredMembershipsCsaCloudSecurityAllianceImage.svg";export { default as PurposeOfProductCertificationImage } from "./PurposeOfProductCertificationImage.svg";
export { default as IgRequiredMembershipsCsaCloudSecurityAllianceWhereToApplyImage } from "./IgRequiredMembershipsCsaCloudSecurityAllianceWhereToApplyImage.svg";
export { default as IgRequiredMembershipsCsaCloudSecurityAllianceEligibilityCriteriaGdprImage } from "./IgRequiredMembershipsCsaCloudSecurityAllianceEligibilityCriteriaGdprImage.svg";
export { default as IgRequiredMembershipsCsaCloudSecurityAllianceApplicationProcessImage } from "./IgRequiredMembershipsCsaCloudSecurityAllianceApplicationProcessImage.svg";
export { default as IgRequiredMembershipsCsaCloudSecurityAllianceRequiredDocumentsImage } from "./IgRequiredMembershipsCsaCloudSecurityAllianceRequiredDocumentsImage.svg";
export { default as IgRequiredMembershipsCsaCloudSecurityAllianceCostBreakdownImage } from "./IgRequiredMembershipsCsaCloudSecurityAllianceCostBreakdownImage.svg";
export { default as IgRequiredMembershipsCsaCloudSecurityAllianceTimelineForCertificationImage } from "./IgRequiredMembershipsCsaCloudSecurityAllianceTimelineForCertificationImage.svg";
export { default as IgRequiredMembershipsCsaCloudSecurityAllianceValidityOfTheCertificateImage } from "./IgRequiredMembershipsCsaCloudSecurityAllianceValidityOfTheCertificateImage.svg";
export { default as IgRequiredMembershipsBsiBritishStandardsInstitutionPurposeOfProductCertificationImage } from "./IgRequiredMembershipsBsiBritishStandardsInstitutionPurposeOfProductCertificationImage.svg";
export { default as IgRequiredMembershipsBsiBritishStandardsInstitutionWhereToApplyImage } from "./IgRequiredMembershipsBsiBritishStandardsInstitutionWhereToApplyImage.svg";
export { default as IgRequiredMembershipsBsiBritishStandardsInstitutionEligibilityCriteriaImage } from "./IgRequiredMembershipsBsiBritishStandardsInstitutionEligibilityCriteriaImage.svg";
export { default as IgRequiredMembershipsBsiBritishStandardsInstitutionApplicationProcessImage } from "./IgRequiredMembershipsBsiBritishStandardsInstitutionApplicationProcessImage.svg";
export { default as IgRequiredMembershipsBsiBritishStandardsInstitutionRequiredDocumentsImage } from "./IgRequiredMembershipsBsiBritishStandardsInstitutionRequiredDocumentsImage.svg";
export { default as IgRequiredMembershipsBsiBritishStandardsInstitutionCostBreakdownImage } from "./IgRequiredMembershipsBsiBritishStandardsInstitutionCostBreakdownImage.svg";
export { default as IgRequiredMembershipsBsiBritishStandardsInstitutionTimelineForCertificationImage } from "./IgRequiredMembershipsBsiBritishStandardsInstitutionTimelineForCertificationImage.svg";
export { default as IgRequiredMembershipsBsiBritishStandardsInstitutionValidityOfTheCertificateImage } from "./IgRequiredMembershipsBsiBritishStandardsInstitutionValidityOfTheCertificateImage.svg";
export { default as IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersWhereToApplyImage } from "./IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersWhereToApplyImage.svg";
export { default as IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersPurposeOfProductCertificationImage } from "./IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersPurposeOfProductCertificationImage.svg";
export { default as IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersEligibilityCriteriaImage } from "./IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersEligibilityCriteriaImage.svg";
export { default as IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersApplicationProcessImage } from "./IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersApplicationProcessImage.svg";
export { default as IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersRequiredDocumentsImage } from "./IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersRequiredDocumentsImage.svg";
export { default as IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersCostBreakdownImage } from "./IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersCostBreakdownImage.svg";
export { default as IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersTimelineForCertificationImage } from "./IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersTimelineForCertificationImage.svg";
export { default as IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersValidityOfTheCertificateImage } from "./IgRequiredMembershipsNabpsNationalAssociationOfBackgroundScreenersValidityOfTheCertificateImage.svg";
export { default as IgRequiredMembershipsUkFinancePurposeOfProductCertificationImage } from "./IgRequiredMembershipsUkFinancePurposeOfProductCertificationImage.svg";
export { default as IgRequiredMembershipsUkFinanceWhereToApplyImage } from "./IgRequiredMembershipsUkFinanceWhereToApplyImage.svg";
export { default as IgRequiredMembershipsUkFinanceEligibilityCriteriaImage } from "./IgRequiredMembershipsUkFinanceEligibilityCriteriaImage.svg";
export { default as IgRequiredMembershipsUkFinanceApplicationProcessImage } from "./IgRequiredMembershipsUkFinanceApplicationProcessImage.svg";
export { default as IgRequiredMembershipsUkFinanceRequiredDocumentsImage } from "./IgRequiredMembershipsUkFinanceRequiredDocumentsImage.svg";
export { default as IgRequiredMembershipsUkFinanceCostBreakdownImage } from "./IgRequiredMembershipsUkFinanceCostBreakdownImage.svg";
export { default as IgRequiredMembershipsUkFinanceTimelineForCertificationImage } from "./IgRequiredMembershipsUkFinanceTimelineForCertificationImage.svg";
export { default as IgRequiredMembershipsUkFinanceValidityOfTheCertificateImage } from "./IgRequiredMembershipsUkFinanceValidityOfTheCertificateImage.svg";
export { default as RequiredAccreditationImage } from "./RequiredAccreditationImage.svg";
export { default as IgRequiredAccrediatiuonUkasPurposeOfProductCertificationImage } from "./IgRequiredAccrediatiuonUkasPurposeOfProductCertificationImage.svg";
export { default as IgRequiredAccrediatiuonUkasWhereToApplyImage } from "./IgRequiredAccrediatiuonUkasWhereToApplyImage.svg";
export { default as IgRequiredAccrediatiuonUkasEligibilityCriteriaImage } from "./IgRequiredAccrediatiuonUkasEligibilityCriteriaImage.svg";
export { default as IgRequiredAccrediatiuonUkasApplicationProcessImage } from "./IgRequiredAccrediatiuonUkasApplicationProcessImage.svg";
export { default as IgRequiredAccrediatiuonUkasRequiredDocumentsImage } from "./IgRequiredAccrediatiuonUkasRequiredDocumentsImage.svg";
export { default as IgRequiredAccrediatiuonUkasCostBreakdownImage } from "./IgRequiredAccrediatiuonUkasCostBreakdownImage.svg";
export { default as IgRequiredAccrediatiuonUkasTimelineForCertificationImage } from "./IgRequiredAccrediatiuonUkasTimelineForCertificationImage.svg";
export { default as IgRequiredAccrediatiuonUkasValidityOfTheCertificateImage } from "./IgRequiredAccrediatiuonUkasValidityOfTheCertificateImage.svg";
export { default as IgRequiredAccrediatiuonCyberEssentialCertificationPurposeOfProductCertificationImage } from "./IgRequiredAccrediatiuonCyberEssentialCertificationPurposeOfProductCertificationImage.svg";
export { default as IgRequiredAccrediatiuonCyberEssentialCertificationWhereToApplyImage } from "./IgRequiredAccrediatiuonCyberEssentialCertificationWhereToApplyImage.svg";
export { default as IgRequiredAccrediatiuonCyberEssentialCertificationEligibilityCriteriaImage } from "./IgRequiredAccrediatiuonCyberEssentialCertificationEligibilityCriteriaImage.svg";
export { default as IgRequiredAccrediatiuonCyberEssentialCertificationApplicationProcessImage } from "./IgRequiredAccrediatiuonCyberEssentialCertificationApplicationProcessImage.svg";
export { default as IgRequiredAccrediatiuonCyberEssentialCertificationRequiredDocumentsImage } from "./IgRequiredAccrediatiuonCyberEssentialCertificationRequiredDocumentsImage.svg";
export { default as IgRequiredAccrediatiuonCyberEssentialCertificationCostBreakdownImage } from "./IgRequiredAccrediatiuonCyberEssentialCertificationCostBreakdownImage.svg";
export { default as IgRequiredAccrediatiuonCyberEssentialCertificationTimelineForCertificationImage } from "./IgRequiredAccrediatiuonCyberEssentialCertificationTimelineForCertificationImage.svg";
export { default as IgRequiredAccrediatiuonCyberEssentialCertificationValidityOfTheCertificateImage } from "./IgRequiredAccrediatiuonCyberEssentialCertificationValidityOfTheCertificateImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec2001PurposeOfProductCertificationImage } from "./IgRequiredAccrediatiuonIsoIec2001PurposeOfProductCertificationImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec2001WhereToApplyImage } from "./IgRequiredAccrediatiuonIsoIec2001WhereToApplyImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec2001EligibilityCriteriaImage } from "./IgRequiredAccrediatiuonIsoIec2001EligibilityCriteriaImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec2001ApplicationProcessImage } from "./IgRequiredAccrediatiuonIsoIec2001ApplicationProcessImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec2001RequiredDocumentsImage } from "./IgRequiredAccrediatiuonIsoIec2001RequiredDocumentsImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec2001CostBreakdownImage } from "./IgRequiredAccrediatiuonIsoIec2001CostBreakdownImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec2001TimelineForCertificationImage } from "./IgRequiredAccrediatiuonIsoIec2001TimelineForCertificationImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec2001ValidityOfTheCertificateImage } from "./IgRequiredAccrediatiuonIsoIec2001ValidityOfTheCertificateImage.svg";
export { default as IgRequiredAccrediatiuonSoc2CompliancePurposeOfProductCertificationImage } from "./IgRequiredAccrediatiuonSoc2CompliancePurposeOfProductCertificationImage.svg";
export { default as IgRequiredAccrediatiuonSoc2ComplianceWhereToApplyImage } from "./IgRequiredAccrediatiuonSoc2ComplianceWhereToApplyImage.svg";
export { default as IgRequiredAccrediatiuonSoc2EligibilityCriteriaGdprImage } from "./IgRequiredAccrediatiuonSoc2EligibilityCriteriaGdprImage.svg";
export { default as IgRequiredAccrediatiuonSoc2ApplicationProcessImage } from "./IgRequiredAccrediatiuonSoc2ApplicationProcessImage.svg";
export { default as IgRequiredAccrediatiuonSoc2RequiredDocumentsImage } from "./IgRequiredAccrediatiuonSoc2RequiredDocumentsImage.svg";
export { default as IgRequiredAccrediatiuonSoc2CostBreakdownImage } from "./IgRequiredAccrediatiuonSoc2CostBreakdownImage.svg";
export { default as IgRequiredAccrediatiuonSoc2TimelineForCertificationImage } from "./IgRequiredAccrediatiuonSoc2TimelineForCertificationImage.svg";
export { default as IgRequiredAccrediatiuonSoc2ValidityOfTheCertificateImage } from "./IgRequiredAccrediatiuonSoc2ValidityOfTheCertificateImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec1974PurposeOfProductCertificationImage } from "./IgRequiredAccrediatiuonIsoIec1974PurposeOfProductCertificationImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec1974WhereToApplyImage } from "./IgRequiredAccrediatiuonIsoIec1974WhereToApplyImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec1974EligibilityCriteriaImage } from "./IgRequiredAccrediatiuonIsoIec1974EligibilityCriteriaImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec1974ApplicationProcessImage } from "./IgRequiredAccrediatiuonIsoIec1974ApplicationProcessImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec1974RequiredDocumentsImage } from "./IgRequiredAccrediatiuonIsoIec1974RequiredDocumentsImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec1974CostBreakdownImage } from "./IgRequiredAccrediatiuonIsoIec1974CostBreakdownImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec1974TimelineForCertificationImage } from "./IgRequiredAccrediatiuonIsoIec1974TimelineForCertificationImage.svg";
export { default as IgRequiredAccrediatiuonIsoIec1974ValidityOfTheCertificateImage } from "./IgRequiredAccrediatiuonIsoIec1974ValidityOfTheCertificateImage.svg";
