// image onebackroute_oneImg.js
export { default as CareQualityCommissionCqcOverviewImage } from "./CareQualityCommissionCqcOverviewImage.svg";

// images multi-page-scricpt.js
export { default as CqcFundamentalStandardsImage } from "./CqcFundamentalStandardsImage.svg";
export { default as img1ScopeOfRegistrationImage } from "./img1ScopeOfRegistrationImage.svg";
export { default as img2ScopeOfRegistrationImage } from "./img2ScopeOfRegistrationImage.svg";
export { default as img3ScopeOfRegistrationImage } from "./img3ScopeOfRegistrationImage.svg";
export { default as IgRequiredLicensesImage } from "./IgRequiredLicensesImage.svg";
export { default as img1IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img1IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
export { default as img2IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img2IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
export { default as img3IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img3IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
export { default as img4IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img4IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
export { default as img5IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img5IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
export { default as img6IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img6IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
export { default as img7IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img7IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
export { default as img8IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage } from "./img8IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemImage.svg";
export { default as IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemPurposeOfProductCertificationImage } from "./IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemPurposeOfProductCertificationImage.svg";
export { default as IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemWhereToApplyImage } from "./IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemWhereToApplyImage.svg";
export { default as IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemEligibilityCriteriaImage } from "./IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemEligibilityCriteriaImage.svg";
export { default as IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemApplicationProcessImage } from "./IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemApplicationProcessImage.svg";
export { default as IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemRequiredDocumentsImage } from "./IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemRequiredDocumentsImage.svg";
export { default as IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemCostBreakdownImage } from "./IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemCostBreakdownImage.svg";
export { default as IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemTimelineForCertificationImage } from "./IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemTimelineForCertificationImage.svg";
export { default as IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemValidityOfTheCertificateImage } from "./IgRequiredAffiliationCifasCreditIndustryFraudAvoidanceSystemValidityOfTheCertificateImage.svg";
